name: Generate Cred Instance
on:
  # Trigger on merging to master.
  push:
    branches:
      - main
  # As well as every 24 hours (at 0:00 UTC).
  schedule:
    - cron: 0 0 * * *

jobs:
  GenerateCredInstance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false # Required to make github pages deployment work correctly

      - name: Cache Data # Cache SourceCred Data, invalidating if any of the config changes or the SC version is updated
        uses: actions/cache@v2.1.6
        with:
          path: '**/cache'
          key: SC-${{ runner.os }}-${{ hashFiles('**/config.json', '**/sourcecred.json', '**/yarn.lock') }}

      - name: Install Packages üîß
        run: yarn --frozen-lockfile

      - name: Load Data and Compute Cred üßÆ
        run: |
          yarn sourcecred go
          yarn sourcecred analysis
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.SOURCECRED_GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}

      - name: Generate Frontend üèó
        run: |
          yarn sourcecred site
          rm -rf ./site/{output,data,config,sourcecred.json}
          cp -r ./{output,data,config,sourcecred.json,package.json,yarn.lock} ./site/

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
